[package]
name = "cargo_atelier"
description = "Cargo integration for the AWS Smithy IDL."
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/cargo_atelier/"
repository = "https://github.com/johnstonskj/rust-atelier.git"
license = "MIT"
readme = "README.md"
publish = true

[dependencies]
atelier_lib = { version = "0.1.0", path = "../atelier-lib" }